## Importación de librerías

In [1]:
!pip install gurobipy pandas

Collecting gurobipy
  Using cached gurobipy-13.0.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (16 kB)
Collecting pandas
  Using cached pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached gurobipy-13.0.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (14.8 MB)
Using cached pandas-3.0.6-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
Using cached numpy-2.5.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Installing collected packages: numpy, gurobipy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]━━━━━━━━━━━ 2/3 [pandas]
Successfully installed gurobipy-13.0.3 numpy-2.5.4 pandas-3.0.6

In [2]:
import sys
import gurobipy as gp
from gurobipy import GRB
import time
import csv
import math
import random
import os
import pandas as pd

print('Python  :', sys.version.split()[0])
print('Gurobi  :', '.'.join(map(str, gp.gurobi.version())))

Python  : 3.14.4
Gurobi  : 13.0.3

### 1. Generación de Datos

In [3]:
# ==========================================
# 1. FUNCIÓN GENERADORA (CALIBRADA Y NO TRIVIAL)
# ==========================================
def generar_instancia_desde_cvrplib(nombre_instancia, datos_clientes, n_clientes=15, tipo_estres="capacidad"):
    N_C = list(range(1, n_clientes + 1))
    n_plus_1 = n_clientes + 1
    N = list(range(n_clientes + 2))
    D = [1, 2, 3]
    R = [1, 2, 3]

    coord_dep = (datos_clientes[0]['x'], datos_clientes[0]['y'])
    coordenadas = {0: coord_dep, n_plus_1: coord_dep}
    for i in N_C:
        coordenadas[i] = (datos_clientes[i]['x'], datos_clientes[i]['y'])

    A = [(i, j) for i in N for j in N if i != j and j != 0 and i != n_plus_1]

    td, tt = {}, {}
    for (i, j) in A:
        dist = math.sqrt((coordenadas[i][0] - coordenadas[j][0])**2 + (coordenadas[i][1] - coordenadas[j][1])**2)
        td[i, j] = round(dist, 2)
        tt[i, j] = round(dist, 2)

    q, st, a, b = {}, {}, {}, {}
    N_TW = []
    var_dia = {1: 1.0, 2: 1.15, 3: 0.90} # Fluctuación semanal

    for i in N_C:
        demanda_base = datos_clientes[i]['demanda']
        for t in D:
            q[i, t] = math.ceil(demanda_base * var_dia[t])
            st[i, t] = 10.0

        tw_inicio = datos_clientes[i]['inicio_tw']
        tw_fin = datos_clientes[i]['fin_tw']
        a[i] = tw_inicio
        b[i] = tw_inicio + max(30, (tw_fin - tw_inicio) * 0.35) if tipo_estres == "tiempo" else tw_fin
        N_TW.append(i)

    # 88% de ocupación para forzar Branch & Bound
    demanda_max_dia = max(sum(q[i, t] for i in N_C) for t in D)
    factor_apriete = 0.88 if tipo_estres == "capacidad" else 0.75
    Q = math.ceil((demanda_max_dia / len(R)) / factor_apriete)

    return {
        'nombre': nombre_instancia, 'A': A, 'N_C': N_C, 'N': N, 'N_TW': N_TW, 'R': R, 'D': D,
        'td': td, 'tt': tt, 'q': q, 'st': st, 'a': a, 'b': b,
        'a_W': datos_clientes[0]['inicio_tw'], 'b_W': datos_clientes[0]['fin_tw'],
        'Q': Q, 'M': 3000.0
    }

# ==========================================
# 2. BANCO DE INSTANCIAS (SOLOMON C101 Y R101)
# ==========================================
datos_solomon_c101 = [
    {'x': 40, 'y': 50, 'demanda': 0, 'inicio_tw': 0, 'fin_tw': 1236},
    {'x': 45, 'y': 68, 'demanda': 10, 'inicio_tw': 100, 'fin_tw': 250},
    {'x': 45, 'y': 70, 'demanda': 25, 'inicio_tw': 150, 'fin_tw': 300},
    {'x': 42, 'y': 66, 'demanda': 15, 'inicio_tw': 65,  'fin_tw': 180},
    {'x': 42, 'y': 68, 'demanda': 12, 'inicio_tw': 200, 'fin_tw': 350},
    {'x': 42, 'y': 65, 'demanda': 18, 'inicio_tw': 45,  'fin_tw': 150},
    {'x': 40, 'y': 69, 'demanda': 20, 'inicio_tw': 250, 'fin_tw': 400},
    {'x': 40, 'y': 66, 'demanda': 15, 'inicio_tw': 120, 'fin_tw': 240},
    {'x': 38, 'y': 68, 'demanda': 22, 'inicio_tw': 180, 'fin_tw': 320},
    {'x': 38, 'y': 70, 'demanda': 10, 'inicio_tw': 300, 'fin_tw': 450},
    {'x': 35, 'y': 66, 'demanda': 14, 'inicio_tw': 80,  'fin_tw': 200},
    {'x': 35, 'y': 69, 'demanda': 16, 'inicio_tw': 220, 'fin_tw': 360},
    {'x': 25, 'y': 85, 'demanda': 20, 'inicio_tw': 350, 'fin_tw': 500},
    {'x': 22, 'y': 75, 'demanda': 28, 'inicio_tw': 50,  'fin_tw': 160},
    {'x': 22, 'y': 85, 'demanda': 12, 'inicio_tw': 280, 'fin_tw': 420},
    {'x': 20, 'y': 80, 'demanda': 35, 'inicio_tw': 150, 'fin_tw': 280}
]

datos_solomon_r101 = [
    {'x': 35, 'y': 35, 'demanda': 0, 'inicio_tw': 0, 'fin_tw': 1000},
    {'x': 41, 'y': 49, 'demanda': 15, 'inicio_tw': 80,  'fin_tw': 180},
    {'x': 35, 'y': 17, 'demanda': 18, 'inicio_tw': 40,  'fin_tw': 120},
    {'x': 55, 'y': 45, 'demanda': 22, 'inicio_tw': 120, 'fin_tw': 220},
    {'x': 55, 'y': 20, 'demanda': 10, 'inicio_tw': 60,  'fin_tw': 150},
    {'x': 15, 'y': 30, 'demanda': 12, 'inicio_tw': 30,  'fin_tw': 110},
    {'x': 25, 'y': 30, 'demanda': 16, 'inicio_tw': 90,  'fin_tw': 200},
    {'x': 20, 'y': 50, 'demanda': 20, 'inicio_tw': 150, 'fin_tw': 260},
    {'x': 10, 'y': 40, 'demanda': 14, 'inicio_tw': 110, 'fin_tw': 210},
    {'x': 55, 'y': 60, 'demanda': 12, 'inicio_tw': 200, 'fin_tw': 310},
    {'x': 30, 'y': 60, 'demanda': 15, 'inicio_tw': 140, 'fin_tw': 240},
    {'x': 20, 'y': 65, 'demanda': 18, 'inicio_tw': 180, 'fin_tw': 290},
    {'x': 50, 'y': 35, 'demanda': 25, 'inicio_tw': 70,  'fin_tw': 160},
    {'x': 30, 'y': 25, 'demanda': 10, 'inicio_tw': 40,  'fin_tw': 130},
    {'x': 15, 'y': 10, 'demanda': 20, 'inicio_tw': 60,  'fin_tw': 150},
    {'x': 60, 'y': 15, 'demanda': 14, 'inicio_tw': 100, 'fin_tw': 200}
]

banco_instancias = {
    "Instancia1_Clustered": {"datos": datos_solomon_c101, "n_clientes": 15},
    "Instancia2_Dispersa": {"datos": datos_solomon_r101, "n_clientes": 15}
}
print("Datos y banco de instancias listos para el bucle.")

Datos y banco de instancias listos para el bucle.

### 2. Definición del Framework Matemático

In [4]:
class ConsistentVRPFramework:
    def __init__(self, data):
        self.data = data
        self.model = None
        self.X, self.Z, self.W, self.dW, self.rW = {}, {}, {}, {}, {}

    def build_model(self):
        self.model = gp.Model("CVRP_Consistent")
        N_C, N, N_TW, R, D = self.data['N_C'], self.data['N'], self.data['N_TW'], self.data['R'], self.data['D']
        td, tt, q, st = self.data['td'], self.data['tt'], self.data['q'], self.data['st']
        a, b, a_W, b_W, Q, M = self.data['a'], self.data['b'], self.data['a_W'], self.data['b_W'], self.data['Q'], self.data['M']
        A = self.data['A']

        self.X = self.model.addVars(A, D, R, vtype=GRB.BINARY, name="X")
        self.Z = self.model.addVars(N_C, R, vtype=GRB.BINARY, name="Z")
        self.W = self.model.addVars(N_C, D, vtype=GRB.CONTINUOUS, lb=0.0, name="W")
        self.dW = self.model.addVars(R, vtype=GRB.CONTINUOUS, lb=0.0, name="dW")
        self.rW = self.model.addVars(R, D, vtype=GRB.CONTINUOUS, lb=0.0, name="rW")

        self.model.setObjective(gp.quicksum(td[i, j] * self.X[i, j, t, r] for (i, j) in A for t in D for r in R), GRB.MINIMIZE)

        for i in N_C:
            self.model.addConstr(gp.quicksum(self.Z[i, r] for r in R) == 1, name=f"AsignacionUnica_{i}")

        for j in N_C:
            for r in R:
                for t in D:
                    self.model.addConstr(gp.quicksum(self.X[i, j, t, r] for i in N if (i, j) in A) == self.Z[j, r], name=f"FlujoEntrada_{j}_{r}_{t}")
        for i in N_C:
            for r in R:
                for t in D:
                    self.model.addConstr(gp.quicksum(self.X[i, j, t, r] for j in N if (i, j) in A) == self.Z[i, r], name=f"FlujoSalida_{i}_{r}_{t}")
        for r in R:
            for t in D:
                 self.model.addConstr(gp.quicksum(self.X[0, j, t, r] for j in N if (0, j) in A) == 1, name=f"SalidaDep_{r}_{t}")

        for r in R:
            for t in D:
                for i in N_C:
                    for j in N_C:
                        if i != j and (i, j) in A:
                            self.model.addConstr(self.W[i, t] + st[i, t] + tt[i, j] <= self.W[j, t] + M * (1 - self.X[i, j, t, r]), name=f"BigM_{i}_{j}_{r}_{t}")

        for i in N_TW:
            for t in D:
                self.model.addConstr(self.W[i, t] >= a[i], name=f"TW_Inicio_{i}_{t}")
                self.model.addConstr(self.W[i, t] <= b[i], name=f"TW_Fin_{i}_{t}")

        n_plus_1 = max(N)
        for j in N_C:
            for r in R:
                for t in D:
                    self.model.addConstr(self.dW[r] + tt[0, j] <= self.W[j, t] + M * (1 - self.X[0, j, t, r]), name=f"CoordSalida_{j}_{r}_{t}")
        for i in N_C:
            for r in R:
                for t in D:
                    self.model.addConstr(self.W[i, t] + st[i, t] + tt[i, n_plus_1] <= self.rW[r, t] + M * (1 - self.X[i, n_plus_1, t, r]), name=f"CoordRet_{i}_{r}_{t}")

        for r in R:
            self.model.addConstr(self.dW[r] >= a_W, name=f"Ap_Dep_{r}")
            for t in D:
                self.model.addConstr(self.rW[r, t] <= b_W, name=f"Ci_Dep_{r}_{t}")
                self.model.addConstr(gp.quicksum(q[i, t] * self.Z[i, r] for i in N_C) <= Q, name=f"Capacidad_{r}_{t}")

        self.model.update()

    def set_base_params(self):
        self.model.resetParams() # LIMPIEZA TOTAL PARA EVITAR EFECTO CASCADA
        self.model.setParam('Threads', 1)
        self.model.setParam('TimeLimit', 600)
        self.model.setParam('OutputFlag', 0)

    def run_relaxation(self):
        self.set_base_params()
        relaxed = self.model.relax()
        relaxed.optimize()
        return relaxed.ObjVal if relaxed.Status == GRB.OPTIMAL else None

    def run_configuration(self, config_name, params_dict):
        self.model.reset()
        self.set_base_params()
        for p, v in params_dict.items():
            self.model.setParam(p, v)

        start = time.time()
        self.model.optimize()
        t = time.time() - start

        if self.model.Status in [GRB.OPTIMAL, GRB.TIME_LIMIT] and self.model.SolCount > 0:
            return self.model.ObjVal, self.model.MIPGap * 100, t
        return None, None, t

    def run_tuning(self, tune_time_limit=300):
        print(" -> Ejecutando Gurobi Tuning...")
        self.model.reset()
        self.set_base_params()
        self.model.setParam('TuneTimeLimit', tune_time_limit)

        start = time.time()
        self.model.tune()

        if self.model.TuneResultCount > 0:
            self.model.getTuneResult(0)
            self.model.optimize()
            t = time.time() - start
            if self.model.SolCount > 0:
                return self.model.ObjVal, self.model.MIPGap * 100, t
        return None, None, time.time() - start

    def run_sensitivity_analysis(self, filename="sensibilidad.csv"):
      if self.model.SolCount == 0:
          print("    [!] No hay solución factible para análisis de sensibilidad.")
          return

      fixed_model = self.model.fixed()
      fixed_model.setParam('OutputFlag', 0)
      fixed_model.setParam('Method', 1)   # Dual Simplex
      fixed_model.setParam('Presolve', 0) # REQUERIDO para habilitar SARHSLow/SARHSUp
      fixed_model.optimize()

      if fixed_model.Status == GRB.OPTIMAL:
          with open(filename, mode='w', newline='', encoding='utf-8') as file:
              writer = csv.writer(file)
              writer.writerow(["Restriccion", "Precio_Sombra_Pi", "SARHSLow", "SARHSUp"])
              for r in self.data['R']:
                  for t in self.data['D']:
                      constr = fixed_model.getConstrByName(f"Capacidad_{r}_{t}")
                      if constr:
                          writer.writerow([f"Cap_{r}_{t}", f"{constr.Pi:.4f}", f"{constr.SARHSLow:.2f}", f"{constr.SARHSUp:.2f}"])
          print(f"    [OK] Sensibilidad guardada en {filename}")

    def exportar_resultados_csv(self, z_LP, res_milp, filename="resultados.csv"):
        with open(filename, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(["Configuracion", "Valor_Objetivo", "Gap_%", "Tiempo_s", "Brecha_Integralidad_%"])

            # Validación explícita de z_LP para evitar errores de formato
            lp_str = f"{z_LP:.4f}" if z_LP is not None else "N/A"
            writer.writerow(["LP Relax", lp_str, "-", "-", "-"])

            z_MILP_base = res_milp.get("Baseline", (None, None, None))[0]

            for config, (obj, gap, run_time) in res_milp.items():
                # Validación estricta usando 'is not None' y previniendo división por cero
                if config == "Baseline" and z_LP is not None and z_MILP_base is not None and z_MILP_base != 0:
                    brecha = f"{((z_MILP_base - z_LP) / z_MILP_base * 100):.2f}"
                else:
                    brecha = "-"

                # Validación explícita para el resto de métricas
                obj_str = f"{obj:.4f}" if obj is not None else "N/A"
                gap_str = f"{gap:.2f}" if gap is not None else "-"

                writer.writerow([config, obj_str, gap_str, f"{run_time:.2f}", brecha])

### 3. Construcción y Ejecución de Experimentos

In [5]:
# ==========================================
# 3. BUCLE DE EXPERIMENTACIÓN AUTOMÁTICA
# ==========================================
tipos_de_estres = ["capacidad"]

for nombre_inst, info in banco_instancias.items():
    for estres in tipos_de_estres:
        sufijo_archivo = f"{nombre_inst}_{estres}"
        print(f"\n==============================================")
        print(f"PROCESANDO: {sufijo_archivo.upper()}")
        print(f"==============================================")

        try:
            # 1. Construir Instancia y Modelo
            data_instancia = generar_instancia_desde_cvrplib(
                nombre_instancia=sufijo_archivo,
                datos_clientes=info["datos"],
                n_clientes=info["n_clientes"],
                tipo_estres=estres
            )
            framework = ConsistentVRPFramework(data_instancia)
            framework.build_model()

            # 2. Relajación LP
            print(" -> Calculando LP Relax...")
            z_LP = framework.run_relaxation()
            print(f"    Valor LP: {z_LP:.2f}" if z_LP else "    Sin solución LP")

            # 3. Configuraciones MILP
            configs = {
                "Baseline": {},
                "No_Cuts": {'Cuts': 0},
                "No_Presolve": {'Presolve': 0},
                "MIPFocus_1": {'MIPFocus': 1},
                "MIPFocus_3": {'MIPFocus': 3},
                "No_Heuristics": {'Heuristics': 0}
            }

            resultados_milp = {}
            for nombre_config, params in configs.items():
                print(f" -> Corriendo MILP: {nombre_config}...")
                obj, gap, t = framework.run_configuration(nombre_config, params)
                resultados_milp[nombre_config] = (obj, gap, t)

            # 4. Gurobi Tuning
            obj_tune, gap_tune, t_tune = framework.run_tuning(tune_time_limit=300)
            resultados_milp["Tuning_Gurobi"] = (obj_tune, gap_tune, t_tune)

            # 5. Análisis de Sensibilidad (Se fuerza correr el Baseline limpio primero)
            print(" -> Preparando Análisis de Sensibilidad...")
            framework.run_configuration("Baseline", {'TimeLimit': 600})
            framework.run_sensitivity_analysis(f"sensibilidad_{sufijo_archivo}.csv")

            # 6. Guardar Resultados
            framework.exportar_resultados_csv(z_LP, resultados_milp, f"resultados_{sufijo_archivo}.csv")
            print(f"[¡OK!] Experimento {sufijo_archivo} completado y guardado con éxito.")

        except Exception as e:
            # Evita que un error mate el código durante la noche
            print(f"\n[ERROR CRÍTICO] Falló el procesamiento de {sufijo_archivo}.")
            print(f"Detalle técnico: {e}")
            print("Saltando automáticamente a la siguiente instancia...")

print("\n¡FIN DE TODOS LOS EXPERIMENTOS!")

==============================================
PROCESANDO: INSTANCIA1_CLUSTERED_CAPACIDAD
==============================================
Set parameter Username
Set parameter LicenseID to value 2874581
Academic license - for non-commercial use only - expires 2027-10-14
 -> Calculando LP Relax...
Reset all parameters
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
    Valor LP: 121.50
 -> Corriendo MILP: Baseline...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Cuts...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Presolve...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: MIPFocus_1...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: MIPFocus_3...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Heuristics...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Ejecutando Gurobi Tuning...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Preparando Análisis de Sensibilidad...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
    [OK] Sensibilidad guardada en sensibilidad_Instancia1_Clustered_capacidad.csv
[¡OK!] Experimento Instancia1_Clustered_capacidad completado y guardado con éxito.

==============================================
PROCESANDO: INSTANCIA2_DISPERSA_CAPACIDAD
==============================================
 -> Calculando LP Relax...
Reset all parameters
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
    Valor LP: 571.29
 -> Corriendo MILP: Baseline...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Cuts...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Presolve...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: MIPFocus_1...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: MIPFocus_3...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Corriendo MILP: No_Heuristics...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
 -> Ejecutando Gurobi Tuning...
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
Gurobi Optimizer version 13.0.3 build v13.0.3rc0 (linux64 - "Ubuntu 26.04 LTS")

CPU model: 12th Gen Intel(R) Core(TM) i7-12700H, instruction set [SSE2|AVX|AVX2]
Thread count: 20 physical cores, 20 logical processors, using up to 1 threads

Non-default parameters:
Threads  1

Optimize a model with 2565 rows, 2271 columns and 11226 nonzeros (Min)
Model fingerprint: 0x95feabf5
Model has 2160 linear objective coefficients
Variable types: 57 continuous, 2214 integer (2214 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+03]
  Objective range  [7e+00, 6e+01]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+03]

Presolve removed 945 rows and 570 columns
Presolve time: 0.01s
Presolved: 1620 rows, 1701 columns, 7461 nonzeros
Variable types: 45 continuous, 1656 integer (1656 binary)

Root relaxation: objective 6.352800e+02, 625 iterations, 0.01 seconds (0.01 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  635.28000    0  120          -  635.28000      -     -    0s
     0     0  644.37096    0  193          -  644.37096      -     -    0s
     0     0  695.28877    0  198          -  695.28877      -     -    0s
     0     0  697.76302    0  155          -  697.76302      -     -    0s
     0     0  697.76302    0  149          -  697.76302      -     -    0s
     0     0  711.63313    0  210          -  711.63313      -     -    0s
     0     0  711.63313    0   76          -  711.63313      -     -    0s
     0     0  711.63313    0   89          -  711.63313      -     -    0s
     0     0  711.63313    0  166          -  711.63313      -     -    0s
     0     0  718.51503    0  150          -  718.51503      -     -    0s
     0     0  722.96243    0  139          -  722.96243      -     -    0s
     0     0  723.59761    0  152          -  723.59761      -     -    0s
     0     0  723.60900    0  142          -  723.60900      -     -    0s
     0     0  723.60900    0  142          -  723.60900      -     -    0s
     0     0  728.74220    0  160          -  728.74220      -     -    0s
H    0     0                    1482.6100000  728.80524  50.8%     -    0s
H    0     0                    1393.5500000  728.80524  47.7%     -    0s
H    0     0                    1348.1500000  728.80524  45.9%     -    0s
H    0     0                    1347.9700000  728.80524  45.9%     -    0s
     0     0  731.01912    0  139 1347.97000  731.01912  45.8%     -    0s
     0     0  731.04492    0  101 1347.97000  731.04492  45.8%     -    0s
     0     0  736.90253    0  178 1347.97000  736.90253  45.3%     -    0s
     0     0  738.40521    0  166 1347.97000  738.40521  45.2%     -    0s
     0     0  738.43213    0  169 1347.97000  738.43213  45.2%     -    0s
     0     0  747.13301    0  167 1347.97000  747.13301  44.6%     -    0s
H    0     0                    1159.0100000  747.16183  35.5%     -    0s
H    0     0                    1139.1500000  747.16183  34.4%     -    0s
     0     0  748.52315    0  171 1139.15000  748.52315  34.3%     -    0s
     0     0  749.03326    0  181 1139.15000  749.03326  34.2%     -    0s
     0     0  749.12407    0  193 1139.15000  749.12407  34.2%     -    0s
     0     0  749.14945    0  173 1139.15000  749.14945  34.2%     -    0s
     0     0  750.73105    0  173 1139.15000  750.73105  34.1%     -    0s
     0     0  750.78582    0  181 1139.15000  750.78582  34.1%     -    0s
     0     0  753.57990    0  172 1139.15000  753.57990  33.8%     -    0s
H    0     0                    1128.7400000  753.66293  33.2%     -    0s
H    0     0                    1127.7800000  753.66293  33.2%     -    0s
H    0     0                    1107.4600000  753.66293  31.9%     -    0s
H    0     0                    1104.5500000  753.66293  31.8%     -    0s
H    0     0                    1103.4000000  753.66293  31.7%     -    0s
H    0     0                    1079.5900000  753.66293  30.2%     -    0s
H    0     0                    1068.0900000  753.66293  29.4%     -    0s
     0     0  754.29614    0  168 1068.09000  754.29614  29.4%     -    0s
     0     0  754.78304    0  198 1068.09000  754.78304  29.3%     -    0s
     0     0  754.82540    0  217 1068.09000  754.82540  29.3%     -    0s
     0     0  757.89538    0  186 1068.09000  757.89538  29.0%     -    0s
H    0     0                    1064.7100000  757.99029  28.8%     -    0s
     0     0  757.99029    0  186 1064.71000  757.99029  28.8%     -    0s
     0     0  758.16826    0  197 1064.71000  758.16826  28.8%     -    0s
     0     0  758.21824    0  193 1064.71000  758.21824  28.8%     -    0s
     0     0  758.71367    0  186 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  188 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  194 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  194 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  188 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  185 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  185 1064.71000  758.71367  28.7%     -    0s
     0     0  758.71367    0  184 1064.71000  758.71367  28.7%     -    0s
     0     2  759.16634    0  184 1064.71000  759.16634  28.7%     -    0s
H    2     2                    1019.9900000  759.16634  25.6%  61.5    0s
H    2     2                    1005.0900000  759.16634  24.5%  61.5    0s
H    9     7                     976.5900000  759.16634  22.3%  66.7    0s
* 1035   566              38     968.3800000  781.07395  19.3%  38.4    2s
H 1185   542                     953.4600000  787.23070  17.4%  38.5    3s
H 1208   527                     950.0800000  787.23070  17.1%  38.9    3s
H 1223   501                     948.3900000  790.45437  16.7%  38.8    3s
* 1321   491              39     938.2000000  793.17906  15.5%  38.6    3s
H 1380   460                     931.3100000  795.48959  14.6%  38.7    3s
H 1520   443                     929.0700000  798.99670  14.0%  39.3    3s
H 1520   420                     925.7600000  798.99670  13.7%  39.3    3s
H 1802   454                     916.7500000  810.18973  11.6%  40.3    4s
* 1806   445              27     915.0600000  810.18973  11.5%  40.2    4s
  2406   552  843.50573   22   87  915.06000  829.00464  9.40%  40.6    5s
H 3399   649                     914.9400000  845.61457  7.58%  39.3    6s
H 3941   647                     913.9000000  854.84375  6.46%  38.3    6s
H 3941   596                     906.2600000  854.84375  5.67%  38.3    6s
H 4526   447                     899.6400000  867.11469  3.62%  37.6    7s

Cutting planes:
  Learned: 33
  Gomory: 4
  Cover: 94
  Implied bound: 73
  Projected implied bound: 19
  Clique: 30
  MIR: 9
  Flow cover: 10
  GUB cover: 3
  Inf proof: 7
  Zero half: 38
  RLT: 13
  Relax-and-lift: 12
  BQP: 5

Explored 5216 nodes (192665 simplex iterations) in 8.17 seconds (11.22 work units)
Thread count was 1 (of 20 available processors)

Solution count 10: 899.64 906.26 913.9 ... 938.2

Optimal solution found (tolerance 1.00e-04)
Best objective 8.996400000000e+02, best bound 8.995700000000e+02, gap 0.0078%
 -> Preparando Análisis de Sensibilidad...
Discarded solution information
Reset all parameters
Set parameter Threads to value 1
Set parameter TimeLimit to value 600
    [OK] Sensibilidad guardada en sensibilidad_Instancia2_Dispersa_capacidad.csv
[¡OK!] Experimento Instancia2_Dispersa_capacidad completado y guardado con éxito.

¡FIN DE TODOS LOS EXPERIMENTOS!

### 4. Visualización de resultados

In [8]:
# ==========================================
# 4. VISUALIZACIÓN DE RESULTADOS
# ==========================================
# Cambia a "Instancia2_Dispersa_capacidad" para ver la otra
nombre_ver = "Instancia1_Clustered_capacidad"

print(f"--- Resultados: {nombre_ver} ---")
archivo_resultados = f"resultados_{nombre_ver}.csv"

if os.path.exists(archivo_resultados):
    display(pd.read_csv(archivo_resultados))
else:
    print(f"[!] No se encontró el archivo: {archivo_resultados}")

print(f"\n--- Sensibilidad: {nombre_ver} ---")
archivo_sensibilidad = f"sensibilidad_{nombre_ver}.csv"

if os.path.exists(archivo_sensibilidad):
    display(pd.read_csv(archivo_sensibilidad).head(10))
else:
    print(f"[!] No se generó el archivo de sensibilidad para {nombre_ver}.")

--- Resultados: Instancia1_Clustered_capacidad ---

   Configuracion  Valor_Objetivo  Gap_% Tiempo_s Brecha_Integralidad_%
0       LP Relax          121.50      -        -                     -
1       Baseline          519.03  13.22   600.00                 76.59
2        No_Cuts          519.03  23.40   600.00                     -
3    No_Presolve          519.03  25.71   600.00                     -
4     MIPFocus_1          519.03  20.72   600.00                     -
5     MIPFocus_3          519.03  10.52   600.00                     -
6  No_Heuristics          520.38  11.32   600.00                     -
7  Tuning_Gurobi             NaN      -   600.19                     -

--- Sensibilidad: Instancia1_Clustered_capacidad ---

  Restriccion  Precio_Sombra_Pi  SARHSLow  SARHSUp
0     Cap_1_1               0.0      95.0      inf
1     Cap_1_2               0.0     112.0      inf
2     Cap_1_3               0.0      88.0      inf
3     Cap_2_1               0.0      95.0      inf
4     Cap_2_2               0.0     111.0      inf
5     Cap_2_3               0.0      87.0      inf
6     Cap_3_1               0.0      82.0      inf
7     Cap_3_2               0.0      97.0      inf
8     Cap_3_3               0.0      75.0      inf

### 5.Analisis de los datos

#### Resultados de los experimentos

In [2]:
import pandas as pd

In [5]:
BASE_EXPERIMENTOS = r"resultados_experimentos/"

In [6]:
resultados_1 = pd.read_csv(BASE_EXPERIMENTOS + "resultados_Instancia1_Clustered_capacidad.csv")
resultados_2 = pd.read_csv(BASE_EXPERIMENTOS + "resultados_Instancia2_Dispersa_capacidad.csv")

In [7]:
resultados_1

   Configuracion  Valor_Objetivo  Gap_% Tiempo_s Brecha_Integralidad_%
0       LP Relax          121.50      -        -                     -
1       Baseline          519.03  13.22   600.00                 76.59
2        No_Cuts          519.03  23.40   600.00                     -
3    No_Presolve          519.03  25.71   600.00                     -
4     MIPFocus_1          519.03  20.72   600.00                     -
5     MIPFocus_3          519.03  10.52   600.00                     -
6  No_Heuristics          520.38  11.32   600.00                     -
7  Tuning_Gurobi             NaN      -   600.19                     -

In [8]:
resultados_2

   Configuracion  Valor_Objetivo Gap_% Tiempo_s Brecha_Integralidad_%
0       LP Relax          571.29     -        -                     -
1       Baseline          899.64  0.01     8.07                 36.50
2        No_Cuts          899.64  0.00    27.96                     -
3    No_Presolve          899.64  0.00   127.60                     -
4     MIPFocus_1          899.64  0.00    11.38                     -
5     MIPFocus_3          899.64  0.01    14.35                     -
6  No_Heuristics          899.64  0.00     7.21                     -
7  Tuning_Gurobi          899.64  0.01   293.66                     -

#### Análisis de sensibilidad

In [10]:
sensibilidad_1 = pd.read_csv(BASE_EXPERIMENTOS + "sensibilidad_Instancia1_Clustered_capacidad.csv")
sensibilidad_2 = pd.read_csv(BASE_EXPERIMENTOS + "sensibilidad_Instancia2_Dispersa_capacidad.csv")

In [11]:
sensibilidad_1

  Restriccion  Precio_Sombra_Pi  SARHSLow  SARHSUp
0     Cap_1_1               0.0      95.0      inf
1     Cap_1_2               0.0     112.0      inf
2     Cap_1_3               0.0      88.0      inf
3     Cap_2_1               0.0      95.0      inf
4     Cap_2_2               0.0     111.0      inf
5     Cap_2_3               0.0      87.0      inf
6     Cap_3_1               0.0      82.0      inf
7     Cap_3_2               0.0      97.0      inf
8     Cap_3_3               0.0      75.0      inf

In [12]:
sensibilidad_2

  Restriccion  Precio_Sombra_Pi  SARHSLow  SARHSUp
0     Cap_1_1               0.0      86.0      inf
1     Cap_1_2               0.0     102.0      inf
2     Cap_1_3               0.0      79.0      inf
3     Cap_2_1               0.0      91.0      inf
4     Cap_2_2               0.0     107.0      inf
5     Cap_2_3               0.0      84.0      inf
6     Cap_3_1               0.0      64.0      inf
7     Cap_3_2               0.0      75.0      inf
8     Cap_3_3               0.0      59.0      inf